# Generated by Django 5.0.0 on 2024-01-01 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('complaint_created', 'Complaint Created'), ('complaint_assigned', 'Complaint Assigned'), ('complaint_forwarded', 'Complaint Forwarded'), ('complaint_commented', 'Complaint Commented'), ('complaint_replied', 'Complaint Replied'), ('complaint_status_changed', 'Complaint Status Changed'), ('withdrawal_submitted', 'Withdrawal Request Submitted'), ('withdrawal_reviewed', 'Withdrawal Request Reviewed'), ('feedback_submitted', 'Feedback Submitted'), ('system_announcement', 'System Announcement')], max_length=30)),
                ('link', models.URLField(blank=True, help_text='Link to related resource', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='complaints.complaint')),
                ('related_withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='complaints.withdrawalrequest')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]

