# Generated by Django 5.0.0 on 2024-01-01 00:05

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Analytics app doesn't have models, just views and utilities
        # This is an empty initial migration
    ]

